version: 0.0 #CodeDeploy 버전, 프로젝트 버전이 아니므로 0.0외에 버전을 사용하면 오류
os: linux
files:
  - source: / #CodeDeploy에서 전달해 준 파일 중 destination으로 이동 시킬 대상 지정, 현재 루트 경로(/)
    destination: /home/ec2-user/app/step3/zip/ #source에서 지정된 파일을 받을 위치, 이후 Jar를 실행하는 등은 destination에서 옮긴 파일들로 진행
    overwrite: yes # 기존에 파일들이 있으면 덮어 쓸지를 결정

permissions: #CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다.
  - object : /
    pattern : "**"
    owner : ec2-user
    group : ec2-user

#CodeDeploy 배포단계에서 실행할 명령어를 지정한다.
#AppicationStart 라는 단계에서 deploy.sh를 ec2-user권한으로 실행하게 한다.
#timeout 60으로 스크립트 실행 60초 이상 수행되면 실패한다.
hooks:
  ApplicationStart:
    - location : deploy.sh
      timeout : 60
      runas : ec2-user